paths:
  /api/product:
    get:
      summary: Obtiene todos los productos
      tags:
        - products
      responses:
        200:
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/products'
        500:
          description: Error interno del servidor, usualmente generado por una query defectuosa.
      
  /api/product/{pid}:
    get:
      summary: Obtiene un solo producto por su ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            $type: String
      responses:
        200:
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Products'
    put:
      summary: Actualizar un producto por su ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
    delete:
      summary: Eliminar un Producto por su ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            $type: String
      responses:
        200:
          description: Producto eliminado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: String
                    example: success
                  message:
                    type: String
                    example: Product deleted
components:
  schemas:
    products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado por MongoDB
        titulo:
          type: String
          description: Nombre del producto
        categoria:
          type: String
          description: categoria del producto
        precio:
          type: Number
          description: precio del producto
        stock:
          type: Number
          description: unidades disponibles del producto
        imagenes:
          type: array
          description: imagenes del producto
      example:
        _id: 6546924fc61d101fcba36f42
        titulo: Aceite de cbd
        categoria: Aceites
        precio: 2000
        stock: 100
        imagenes: []
  requestBodies:
    updateProduct:
      type: object
      properties:
        titulo:
          type: String
          description: Nombre del producto
        categoria:
          type: String
          description: categoria del producto
        precio:
          type: Number
          description: precio del producto
        stock:
          type: Number
          description: unidades disponibles del producto
        imagenes:
          type: array
          description: imagenes del producto
      example:
        titulo: Aceite de cbd
        categoria: Aceites
        precio: 2000
        stock: 100
        imagenes: []